const deepFreeze = (value) => {
  Object.freeze(value);
  Object.values(value).forEach((child) => {
    if (child && typeof child === 'object' && !Object.isFrozen(child)) deepFreeze(child);
  });
  return value;
};

export const ENEMY_CONFIGS = deepFreeze({
  trooper: {
    id: 'trooper',
    name: 'Контурный стрелок',
    role: 'ranged',
    description: 'Держит среднюю дистанцию и атакует короткими очередями.',
    health: 72,
    maxHealth: 72,
    shield: 0,
    speed: 4.1,
    acceleration: 12,
    turnSpeed: 6,
    radius: 0.42,
    height: 1.7,
    sightRange: 34,
    hearingRange: 18,
    fieldOfView: 115,
    perception: { distance: 34, fov: 115, memory: 4.5 },
    memoryDuration: 4.5,
    preferredRange: 18,
    retreatRange: 7,
    attackRange: 30,
    damage: 9,
    attackCooldown: 0.72,
    burstCount: 3,
    burstInterval: 0.12,
    telegraphTime: 0.2,
    accuracy: 0.72,
    projectileSpeed: 48,
    staggerThreshold: 26,
    spawnCost: 2,
    score: 100,
    experience: 18,
    color: '#ffad45',
  },
  hunter: {
    id: 'hunter',
    name: 'Фазовый охотник',
    role: 'flanker',
    description: 'Обходит игрока, телеграфирует рывок и наказывает за неподвижность.',
    health: 118,
    maxHealth: 118,
    shield: 20,
    speed: 5.8,
    acceleration: 18,
    turnSpeed: 8,
    radius: 0.5,
    height: 1.45,
    sightRange: 38,
    hearingRange: 24,
    fieldOfView: 145,
    perception: { distance: 38, fov: 145, memory: 7 },
    memoryDuration: 7,
    preferredRange: 7,
    retreatRange: 2.2,
    attackRange: 13,
    damage: 24,
    attackCooldown: 1.8,
    burstCount: 1,
    burstInterval: 0,
    telegraphTime: 0.62,
    accuracy: 0.9,
    projectileSpeed: 0,
    dashSpeed: 15,
    dashDuration: 0.32,
    staggerThreshold: 42,
    spawnCost: 4,
    score: 260,
    experience: 42,
    color: '#ca69ff',
  },
  warden: {
    id: 'warden',
    name: 'Страж Разлома',
    role: 'elite',
    description: 'Многофазовый хранитель со щитом, рывком и опасными зонами.',
    health: 920,
    maxHealth: 920,
    shield: 280,
    speed: 3.65,
    acceleration: 10,
    turnSpeed: 4.2,
    radius: 0.9,
    height: 2.8,
    sightRange: 52,
    hearingRange: 44,
    fieldOfView: 170,
    perception: { distance: 52, fov: 170, memory: 12 },
    memoryDuration: 12,
    preferredRange: 16,
    retreatRange: 6,
    attackRange: 44,
    damage: 30,
    attackCooldown: 2.2,
    burstCount: 5,
    burstInterval: 0.14,
    telegraphTime: 0.85,
    accuracy: 0.82,
    projectileSpeed: 36,
    dashSpeed: 12,
    dashDuration: 0.55,
    hazardRadius: 5.5,
    hazardDamage: 18,
    hazardDuration: 4.5,
    phaseThresholds: [0.66, 0.33],
    staggerThreshold: 110,
    spawnCost: 18,
    score: 3000,
    experience: 400,
    color: '#f34c8f',
  },
});

export default ENEMY_CONFIGS;
