const deepFreeze = (value) => {
  Object.freeze(value);
  for (const child of Object.values(value)) {
    if (child && typeof child === 'object' && !Object.isFrozen(child)) deepFreeze(child);
  }
  return value;
};

export const DIFFICULTY_CONFIGS = deepFreeze({
  easy: {
    id: 'easy',
    name: 'Оператор',
    description: 'Больше ресурсов и более читаемые атаки противников.',
    enemyHealthMultiplier: 0.9,
    enemyDamageMultiplier: 0.75,
    enemySpeedMultiplier: 0.92,
    reactionTimeMultiplier: 1.35,
    accuracyMultiplier: 0.72,
    attackCooldownMultiplier: 1.25,
    groupSizeMultiplier: 0.82,
    resourceMultiplier: 1.35,
    directorIntensityMultiplier: 0.82,
    eventFrequencyMultiplier: 0.9,
  },
  normal: {
    id: 'normal',
    name: 'Вектор',
    description: 'Рекомендуемый темп и состав волн.',
    enemyHealthMultiplier: 1,
    enemyDamageMultiplier: 1,
    enemySpeedMultiplier: 1,
    reactionTimeMultiplier: 1,
    accuracyMultiplier: 1,
    attackCooldownMultiplier: 1,
    groupSizeMultiplier: 1,
    resourceMultiplier: 1,
    directorIntensityMultiplier: 1,
    eventFrequencyMultiplier: 1,
  },
  hard: {
    id: 'hard',
    name: 'Разлом',
    description: 'Быстрая реакция, точное позиционирование и агрессивный директор.',
    enemyHealthMultiplier: 1.08,
    enemyDamageMultiplier: 1.22,
    enemySpeedMultiplier: 1.08,
    reactionTimeMultiplier: 0.72,
    accuracyMultiplier: 1.28,
    attackCooldownMultiplier: 0.8,
    groupSizeMultiplier: 1.18,
    resourceMultiplier: 0.75,
    directorIntensityMultiplier: 1.3,
    eventFrequencyMultiplier: 1.16,
  },
});

export const GAME_CONFIG = deepFreeze({
  id: 'vector-null',
  title: 'VECTOR//NULL',
  version: '0.1.0',
  defaultDifficulty: 'normal',
  difficulties: DIFFICULTY_CONFIGS,
  fixedTimeStep: 1 / 60,
  fixedStep: 1 / 60,
  maxFrameDelta: 0.1,
  maxDelta: 0.1,
  maxSubSteps: 5,
  targetFps: 60,
  run: {
    targetDurationSeconds: 420,
    scorePerSecond: 2,
    scorePerObjective: 1250,
    scorePerShift: 400,
    phases: [
      { id: 'recon', name: 'Разведка', start: 0, duration: 70, intensity: 0.55 },
      { id: 'escalation', name: 'Эскалация', start: 70, duration: 90, intensity: 0.82 },
      { id: 'shift', name: 'Сдвиг', start: 160, duration: 80, intensity: 1 },
      { id: 'hunt', name: 'Охота', start: 240, duration: 100, intensity: 1.2 },
      { id: 'finale', name: 'Финал', start: 340, duration: 80, intensity: 1.42 },
    ],
  },
  player: {
    maxHealth: 100,
    height: 1.8,
    radius: 0.42,
    mass: 8,
    maxShield: 35,
    maxArmor: 100,
    startingArmor: 35,
    armorAbsorption: 0.62,
    shieldRechargeDelay: 4,
    shieldRechargeRate: 14,
    moveSpeed: 7.4,
    walkSpeed: 7.4,
    sprintSpeed: 11.2,
    crouchSpeed: 4.2,
    airControl: 0.32,
    groundAcceleration: 48,
    groundDeceleration: 42,
    airAcceleration: 10,
    jumpVelocity: 7.4,
    jumpSpeed: 7.4,
    gravity: 22,
    coyoteTime: 0.12,
    jumpBufferTime: 0.14,
    standingHeight: 1.78,
    crouchingHeight: 1.08,
    standingEyeOffset: 0.72,
    crouchingEyeOffset: 0.28,
    mouseSensitivity: 0.00215,
    maxPitch: Math.PI * 0.485,
    dashSpeed: 18,
    dashDuration: 0.18,
    dashCooldown: 1.8,
    slideDuration: 0.72,
    slideSpeed: 13.2,
    slideCooldown: 0.55,
    headBob: true,
    headBobScale: 1,
    interactionRange: 3.2,
  },
  camera: {
    fov: 90,
    sprintFov: 98,
    near: 0.05,
    far: 260,
    bobFrequency: 10,
    bobAmplitude: 0.025,
  },
  physics: {
    gravity: [0, -22, 0],
    solverIterations: 10,
    contactEquationRelaxation: 3,
    defaultFriction: 0.08,
  },
  arena: {
    size: 72,
    ceilingHeight: 14,
    cellSize: 6,
    safeSpawnRadius: 12,
    enemySpawnMinDistance: 15,
    enemySpawnMaxDistance: 42,
    maxDynamicSections: 8,
  },
  director: {
    tickInterval: 0.25,
    initialBudget: 5,
    maxBudget: 24,
    budgetPerSecond: 0.12,
    maxActiveEnemies: 28,
    maxConcurrentAttackers: 4,
    reliefHealthThreshold: 0.32,
    reliefDuration: 8,
  },
  realityShift: {
    firstDelay: 65,
    intervalMin: 60,
    intervalMax: 90,
    warningDuration: 5,
    transitionDuration: 2.5,
    upgradeChoices: 3,
    modifiers: ['lowGravity', 'ionStorm', 'overclock', 'supplyVault'],
  },
  objectives: {
    activationRadius: 2.5,
    holdDuration: 32,
    terminalActivationTime: 2.2,
    fragmentsRequired: 4,
    evacuationHoldDuration: 35,
  },
  rewards: {
    killEnergy: 8,
    eliteEnergy: 50,
    objectiveEnergy: 75,
    experiencePerScore: 0.02,
    firstLevelExperience: 500,
    levelGrowth: 1.22,
  },
});

export default GAME_CONFIG;
