const deepFreeze = (value) => {
  Object.freeze(value);
  Object.values(value).forEach((child) => {
    if (child && typeof child === 'object' && !Object.isFrozen(child)) deepFreeze(child);
  });
  return value;
};

export const WEAPON_CONFIGS = deepFreeze({
  carbine: {
    id: 'carbine',
    name: 'VX-9 Импульс',
    shortName: 'VX-9',
    description: 'Стабильный автоматический карабин для боя на средней дистанции.',
    type: 'hitscan',
    damage: 18,
    fireRate: 9.2,
    magazine: 30,
    reserve: 180,
    reloadTime: 1.65,
    spread: 0.006,
    moveSpread: 0.014,
    adsSpread: 0.0015,
    recoil: { pitch: 0.018, yaw: 0.007, recovery: 12 },
    range: 82,
    falloffStart: 28,
    falloffEnd: 72,
    automatic: true,
    pellets: 1,
    headMultiplier: 1.65,
    color: '#63f4df',
    equipTime: 0.3,
    adsFovMultiplier: 0.82,
    tracerEvery: 3,
    sound: 'carbineShot',
  },
  scatter: {
    id: 'scatter',
    name: 'SG-4 Осколок',
    shortName: 'SG-4',
    description: 'Кинетический рассеиватель с сильным импульсом в ближнем бою.',
    type: 'shotgun',
    damage: 13,
    fireRate: 1.25,
    magazine: 7,
    reserve: 49,
    reloadTime: 2.15,
    spread: 0.052,
    moveSpread: 0.07,
    adsSpread: 0.032,
    recoil: { pitch: 0.072, yaw: 0.018, recovery: 8 },
    range: 34,
    falloffStart: 9,
    falloffEnd: 27,
    automatic: false,
    pellets: 9,
    headMultiplier: 1.25,
    color: '#ffb547',
    equipTime: 0.42,
    adsFovMultiplier: 0.88,
    tracerEvery: 1,
    sound: 'scatterShot',
  },
  rail: {
    id: 'rail',
    name: 'ARX Нуль-копьё',
    shortName: 'ARX',
    description: 'Медленный высокоточный энергетический импульс для дальнего боя.',
    type: 'hitscan',
    damage: 92,
    fireRate: 0.72,
    magazine: 4,
    reserve: 24,
    reloadTime: 2.6,
    spread: 0.001,
    moveSpread: 0.011,
    adsSpread: 0,
    recoil: { pitch: 0.095, yaw: 0.003, recovery: 6.5 },
    range: 130,
    falloffStart: 75,
    falloffEnd: 125,
    automatic: false,
    pellets: 1,
    headMultiplier: 2,
    color: '#c374ff',
    equipTime: 0.5,
    adsFovMultiplier: 0.72,
    tracerEvery: 1,
    sound: 'railShot',
  },
  plasma: {
    id: 'plasma',
    name: 'PX-7 Поток',
    shortName: 'PX-7',
    description: 'Компактный плазменный автомат: шквал ярких импульсов, высокая мобильность и контроль ближней дистанции.',
    type: 'hitscan',
    model: 'plasma-smg',
    damage: 10.5,
    fireRate: 16,
    magazine: 48,
    reserve: 288,
    reloadTime: 1.9,
    spread: 0.009,
    moveSpread: 0.019,
    adsSpread: 0.003,
    spreadGrowth: 0.0023,
    recoil: { pitch: 0.009, yaw: 0.004, recovery: 17 },
    range: 62,
    falloffStart: 18,
    falloffEnd: 54,
    minDamageMultiplier: 0.52,
    automatic: true,
    pellets: 1,
    headMultiplier: 1.45,
    color: '#35a7ff',
    equipTime: 0.26,
    adsFovMultiplier: 0.86,
    tracerEvery: 1,
    loudness: 0.88,
    sound: 'plasmaShot',
    viewModel: {
      muzzleZ: -0.86,
      basePosition: [0.4, -0.34, -0.68],
      adsPosition: [0, -0.235, -0.57],
      scale: 0.9,
      kick: 0.34,
    },
    vfx: { tracerWidth: 1.28, muzzleIntensity: 0.92, impactCount: 5 },
  },
  nova: {
    id: 'nova',
    name: 'HMX-1 Сверхнова',
    shortName: 'HMX-1',
    description: 'Тяжёлая имплозионная пушка. Медленный заряд детонирует в точке попадания и накрывает группу целей.',
    type: 'explosive-hitscan',
    model: 'nova-cannon',
    damage: 72,
    fireRate: 0.52,
    magazine: 3,
    reserve: 18,
    reloadTime: 2.9,
    spread: 0.003,
    moveSpread: 0.025,
    adsSpread: 0.0005,
    recoil: { pitch: 0.12, yaw: 0.008, recovery: 5 },
    range: 95,
    falloffStart: 48,
    falloffEnd: 92,
    minDamageMultiplier: 0.65,
    automatic: false,
    pellets: 1,
    headMultiplier: 1.15,
    color: '#ff6538',
    equipTime: 0.62,
    adsFovMultiplier: 0.78,
    tracerEvery: 1,
    loudness: 1.65,
    sound: 'novaShot',
    impactBlast: { radius: 5.2, damage: 46, color: '#ff6538' },
    viewModel: {
      muzzleZ: -1.18,
      basePosition: [0.47, -0.39, -0.78],
      adsPosition: [0, -0.27, -0.69],
      scale: 0.95,
      kick: 1.85,
    },
    vfx: { tracerWidth: 2.35, muzzleIntensity: 2.1, impactCount: 14 },
  },
});

export const WEAPON_ORDER = Object.freeze(['carbine', 'scatter', 'rail', 'plasma', 'nova']);

export default WEAPON_CONFIGS;
