const deepFreeze = (value) => {
  Object.freeze(value);
  Object.values(value).forEach((child) => {
    if (child && typeof child === 'object' && !Object.isFrozen(child)) deepFreeze(child);
  });
  return value;
};

export const WEAPON_CONFIGS = deepFreeze({
  carbine: {
    id: 'carbine',
    name: 'VX-9 Импульс',
    shortName: 'VX-9',
    description: 'Стабильный автоматический карабин для боя на средней дистанции.',
    type: 'hitscan',
    damage: 18,
    fireRate: 9.2,
    magazine: 30,
    reserve: 180,
    reloadTime: 1.65,
    spread: 0.006,
    moveSpread: 0.014,
    adsSpread: 0.0015,
    recoil: { pitch: 0.018, yaw: 0.007, recovery: 12 },
    range: 82,
    falloffStart: 28,
    falloffEnd: 72,
    automatic: true,
    pellets: 1,
    headMultiplier: 1.65,
    color: '#63f4df',
    equipTime: 0.3,
    adsFovMultiplier: 0.82,
    tracerEvery: 3,
    sound: 'carbineShot',
  },
  scatter: {
    id: 'scatter',
    name: 'SG-4 Осколок',
    shortName: 'SG-4',
    description: 'Кинетический рассеиватель с сильным импульсом в ближнем бою.',
    type: 'shotgun',
    damage: 13,
    fireRate: 1.25,
    magazine: 7,
    reserve: 49,
    reloadTime: 2.15,
    spread: 0.052,
    moveSpread: 0.07,
    adsSpread: 0.032,
    recoil: { pitch: 0.072, yaw: 0.018, recovery: 8 },
    range: 34,
    falloffStart: 9,
    falloffEnd: 27,
    automatic: false,
    pellets: 9,
    headMultiplier: 1.25,
    color: '#ffb547',
    equipTime: 0.42,
    adsFovMultiplier: 0.88,
    tracerEvery: 1,
    sound: 'scatterShot',
  },
  rail: {
    id: 'rail',
    name: 'ARX Нуль-копьё',
    shortName: 'ARX',
    description: 'Медленный высокоточный энергетический импульс для дальнего боя.',
    type: 'hitscan',
    damage: 92,
    fireRate: 0.72,
    magazine: 4,
    reserve: 24,
    reloadTime: 2.6,
    spread: 0.001,
    moveSpread: 0.011,
    adsSpread: 0,
    recoil: { pitch: 0.095, yaw: 0.003, recovery: 6.5 },
    range: 130,
    falloffStart: 75,
    falloffEnd: 125,
    automatic: false,
    pellets: 1,
    headMultiplier: 2,
    color: '#c374ff',
    equipTime: 0.5,
    adsFovMultiplier: 0.72,
    tracerEvery: 1,
    sound: 'railShot',
  },
});

export const WEAPON_ORDER = Object.freeze(['carbine', 'scatter', 'rail']);

export default WEAPON_CONFIGS;
